# Generated by Django 6.0.1 on 2026-01-22 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_paiement', models.CharField(max_length=50)),
                ('statut', models.CharField(default='En attente', max_length=50)),
                ('reference_transaction', models.CharField(blank=True, max_length=100, null=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commandes.commande')),
            ],
        ),
    ]
