# Generated by Django 5.2.5 on 2026-02-09 00:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='mode_paiement',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='reference_transaction',
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paiement',
            name='methode',
            field=models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('CARTE', 'Carte bancaire')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=django.utils.timezone.now, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paiement',
            name='reference',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paiement',
            name='user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('INITIE', 'Initié'), ('REUSSI', 'Réussi'), ('ECHEC', 'Échec')], default='INITIE', max_length=20),
        ),
    ]
