# Generated by Django 5.2.5 on 2026-02-09 00:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='paiement',
            old_name='mode_paiement',
            new_name='methode',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='reference_transaction',
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paiement',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paiement',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(default='EN_ATTENTE', max_length=50),
        ),
    ]
