# Generated by Django 5.2.5 on 2026-02-08 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0001_initial'),
        ('products', '0002_categorie_est_populaire_categorie_image_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lignepanier',
            unique_together={('panier', 'produit')},
        ),
    ]
