# Generated by Django 5.2.5 on 2026-01-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='est_populaire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categorie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='produit',
            name='est_populaire',
            field=models.BooleanField(default=False),
        ),
    ]
